# Generated by Django 5.0.8 on 2024-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('students', models.IntegerField(blank=True, null=True)),
                ('teachers', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField()),
                ('departments', models.ManyToManyField(to='Core.department')),
            ],
        ),
    ]
