# Generated by Django 5.0.8 on 2024-10-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_lead_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
