# Generated by Django 5.0.8 on 2024-10-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='confirmed', max_length=25)),
                ('students', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('time_arrival', models.TimeField(blank=True, null=True)),
                ('time_leave', models.TimeField(blank=True, null=True)),
                ('food', models.CharField(blank=True, max_length=50, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.lead')),
            ],
        ),
    ]
