# Generated by Django 5.0.8 on 2024-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
