# Generated by Django 5.0.8 on 2024-10-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_lead_alt_name_lead_alt_number_lead_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='generated',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
    ]
