# Generated by Django 5.0.8 on 2024-10-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_lead_departments_remove_lead_generated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
