# Generated by Django 5.0.8 on 2024-10-16 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_user_mobile'),
        ('Core', '0011_department_lead_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='alt_name',
            new_name='primary_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='alt_number',
            new_name='primary_number',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='contact_name',
            new_name='secondery_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='contact_number',
            new_name='secondery_number',
        ),
        migrations.AddField(
            model_name='lead',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.group'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
