# Generated by Django 5.0.8 on 2024-10-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_rename_alt_name_lead_primary_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='secondery_name',
            new_name='secondary_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='secondery_number',
            new_name='secondary_number',
        ),
    ]
