# Generated by Django 5.0.8 on 2024-10-18 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_rename_secondery_name_lead_secondary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='next_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
