# Generated by Django 5.0.8 on 2024-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_followup_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='next_date',
            field=models.DateField(null=True),
        ),
    ]
