# Generated by Django 5.0.8 on 2024-10-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_group_date_source_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authentication.source'),
        ),
    ]
