# Generated by Django 5.0.8 on 2024-10-16 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_group_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.source'),
        ),
    ]
